---
job: "extension"
config:
  name: "songHye_sxhonzkyx_woman" #Song Hye Kyo
  process:
    - type: "diffusion_trainer"
      training_folder: "/media/justin-wijaya/7d3e3892-cb10-43b8-83b4-a35e3cdf9ab0/justin/Workspace/ai-toolkit/output"
      sqlite_db_path: "./aitk_db.db"
      device: "cuda"
      trigger_word: null
      performance_log_every: 10
      network:
        type: "lokr"
        linear: 32
        linear_alpha: 32
        conv: 16
        conv_alpha: 16
        lokr_full_rank: true
        lokr_factor: -1
        network_kwargs:
          ignore_if_contains: []
      save:
        dtype: "bf16"
        save_every: 250
        max_step_saves_to_keep: 20
        save_format: "safetensors"
        push_to_hub: false
      datasets:
        - folder_path: "/media/justin-wijaya/7d3e3892-cb10-43b8-83b4-a35e3cdf9ab0/justin/Workspace/ai-toolkit/datasets/ltx25/songHye/gold"
          mask_path: null
          mask_min_value: 0.1
          default_caption: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.00
          cache_latents_to_disk: true
          is_reg: true
          network_weight: 1
          resolution:
            - 640
            - 640
          controls: []
          shrink_video_to_frames: true
          num_frames: 57
          flip_x: false
          flip_y: false
          num_repeats: 1
          do_i2v: false
          do_audio: true
          fps: 30
          auto_frame_count: false
      train:
        batch_size: 1
        bypass_guidance_embedding: false
        steps: 3000
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        timestep_type: "weighted"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        unload_text_encoder: true
        cache_text_embeddings: true
        lr: 0.00005
        ema_config:
          use_ema: false
          ema_decay: 0.99
        skip_first_sample: true
        force_first_sample: false
        disable_sampling: true
        dtype: "bf16"
        diff_output_preservation: false
        diff_output_preservation_multiplier: 1
        diff_output_preservation_class: "person"
        switch_boundary_every: 1
        loss_type: "mse"
        audio_loss_multiplier: 1
      logging:
        log_every: 1
        use_ui_logger: true
      model:
        name_or_path: "Lightricks/LTX-2.5"
        quantize: true
        qtype: "convrot8"
        quantize_te: true
        qtype_te: "convrot8"
        arch: "ltx2.5"
        low_vram: true
        model_kwargs: {}
        compile: false
        layer_offloading: true
        layer_offloading_text_encoder_percent: 1
        layer_offloading_transformer_percent: 1
      sample:
        sampler: "flowmatch"
        sample_every: 250
        sample_start_step: 0
        width: 512
        height: 512
        samples:
          - prompt: "woman with red hair, playing chess at the park, bomb going off in the background"
          - prompt: "a woman holding a coffee cup, in a beanie, sitting at a cafe"
          - prompt: "a horse is a DJ at a night club, fish eye lens, smoke machine, lazer lights, holding a martini"
          - prompt: "a man showing off his cool new t shirt at the beach, a shark is jumping out of the water in the background"
          - prompt: "a bear building a log cabin in the snow covered mountains"
          - prompt: "woman playing the guitar, on stage, singing a song, laser lights, punk rocker"
          - prompt: "hipster man with a beard, building a chair, in a wood shop"
          - prompt: "photo of a man, white background, medium shot, modeling clothing, studio lighting, white backdrop"
          - prompt: "a man holding a sign that says, 'this is a sign'"
          - prompt: "a bulldog, in a post apocalyptic world, with a shotgun, in a leather jacket, in a desert, with a motorcycle"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 30
        num_frames: 121
        fps: 30
meta:
  name: "[name]"
  version: "1.0"
